# Generated by Django 5.1.5 on 2025-02-07 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodSugarRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbohydrate_intake', models.FloatField(blank=True, help_text='攝取的碳水 (g)', null=True)),
                ('blood_glucose', models.FloatField(help_text='血糖數據 (mg/dL)')),
                ('exercise_duration', models.FloatField(blank=True, help_text='運動時常 (分鐘)', null=True)),
                ('insulin_injection', models.FloatField(blank=True, help_text='胰島素注射量 (單位)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_slot', models.DateTimeField(help_text='依照固定時段計算的時間槽')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_sugar_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
