# Generated by Django 5.1.4 on 2025-03-11 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodSugarComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_blood_glucose', models.FloatField(help_text='上次血糖值 (mg/dL)')),
                ('current_blood_glucose', models.FloatField(help_text='本次血糖值 (mg/dL)')),
                ('insulin_injection', models.FloatField(blank=True, help_text='胰島素注射量 (單位)', null=True)),
                ('carbohydrate_intake', models.FloatField(blank=True, help_text='碳水攝取量 (g)', null=True)),
                ('time_interval', models.DurationField(help_text='兩次血糖記錄的時間間隔')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_record', models.ForeignKey(help_text='本次的血糖記錄', on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_current', to='getdata.bloodsugarrecord')),
                ('previous_record', models.ForeignKey(help_text='上一次的血糖記錄', on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_previous', to='getdata.bloodsugarrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_sugar_comparisons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserModelConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_consented', models.BooleanField(default=False)),
                ('consent_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model_consent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPersonalizedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_path', models.CharField(blank=True, max_length=255, null=True)),
                ('is_trained', models.BooleanField(default=False)),
                ('last_trained', models.DateTimeField(blank=True, null=True)),
                ('training_data_count', models.IntegerField(default=0)),
                ('model_version', models.IntegerField(default=1)),
                ('model_performance', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_model', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
